
database:
  host: localhost
  port: 16452

server:
  port: 19080

spring:
  jackson:
    serialization.indent_output: true

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
