
database:
  host: ${APP_NAME}_db
  port: 5432

security:
  signKey: 0123456789

spring:
  application:
    name: ${APP_NAME}

  datasource:
    username: ${APP_NAME}
    password: ${APP_NAME}
    url: jdbc:postgresql://${database.host}:${database.port}/${APP_NAME}

  flyway:
    check-location: false
    locations:
      - classpath:db
      - filesystem:${dataImportLocation:data}

  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

  rabbitmq:
    host: rabbit

  cloud:
    stream:
      bindings:
        checkout-input:
          destination: checkout
          group: ${spring.application.name}
        checkout-output:
          destination: checkout
