image: openjdk:8-alpine

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - export GRADLE_OPTS="-Dorg.gradle.daemon=false"

build:
  stage: build
  script: ./gradlew --build-cache classes testClasses assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle

test:
  stage: test
  script: ./gradlew -xitest check
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle
