
database:
  host: localhost
  port: 18432

#reservation:
#  availability: PT10M
#  check-interval: PT60S

server:
  port: 21080

spring:
  jackson:
    serialization.indent_output: true

  rabbitmq:
    host: localhost
