database:
  host: ${APP_NAME}_db
  port: 5432

spring:
  datasource:
    username: ${APP_NAME}
    password: ${APP_NAME}
    url: jdbc:postgresql://${database.host}:${database.port}/${APP_NAME}

  flyway:
    check-location: false
    locations:
      - classpath:db
      - filesystem:${dataImportLocation:data}

  rabbitmq:
    host: rabbit
