version: "3.1"

services:
  rabbit:
    build:
      context: .
      dockerfile: dockerfile.txt
    image: [=repository][=application]:[=tagName]
    container_name: [=name]_[=application]
    volumes:
    - rabbit:/var/lib/rabbitmq
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
    networks:
      - [=network]
[#if publish]
    ports:
      - 5672:5672
      - 15672:15672
[/#if]

volumes:
  rabbit:

networks:
  [=network]:

