version: "3.1"

services:
  rabbit:
    image: "rabbitmq:latest"
    container_name: rabbit
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
    networks:
      - micro-services
    ports:
      - 5672:5672
      - 15672:15672

networks:
  micro-services:

