version: "3.1"

services:
  rabbit:
    image: "rabbitmq:management"
    container_name: rabbit
#    volumes:
#    - rabbit:/var/lib/rabbitmq
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
    networks:
      - micro-services
    ports:
      - 5672:5672
      - 15672:15672

#volumes:
#  rabbit:

networks:
  micro-services:

