
database:
  host: ${APP_NAME}-db
  port: 5432

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: false

security:
  signKey: 0123456789

spring:
  application:
    name: ${APP_NAME}

  datasource:
    username: ${APP_NAME}
    password: ${APP_NAME}
    url: jdbc:postgresql://${database.host}:${database.port}/${APP_NAME}

  flyway:
    check-location: false
    locations:
      - classpath:db
      - filesystem:${dataImportLocation:data}

  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

  rabbitmq:
    host: rabbit
