
database:
  host: localhost
  port: 15442

server:
  port: 18090

spring:
  jackson:
    serialization:
      indent_output: true

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
