
database:
  host: localhost
  port: 18432

reservation:
  availability: 1

server:
  port: 21080

spring:
  jackson:
    serialization.indent_output: true

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  rabbitmq:
    host: localhost
