
database:
  host: db
  port: 5432

spring.datasource:
  username: products
  password: products
  url: jdbc:postgresql://${database.host}:${database.port}/products

spring.jpa.properties.hibernate:
  temp.use_jdbc_metadata_defaults: false
  format_sql: true

spring.flyway:
  locations:
    - classpath:db
    - filesystem:${dataImportLocation}
