
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:48080/services/eureka/}
#  instance:
#    preferIpAddress: true

spring:
  application:
    name: ${APP_NAME}

  main:
    banner-mode: 'off'

zuul:
  routes:
    oauth:
      strip-prefix: false
      sensitive-headers:
      service-id: authz
    users:
      strip-prefix: false
      sensitive-headers:
      service-id: authz
    roles:
      strip-prefix: false
      sensitive-headers:
      service-id: authz
    baskets:
      strip-prefix: false
      sensitive-headers:
      service-id: basket
    customers:
      strip-prefix: false
      sensitive-headers:
      service-id: customer
    checkouts:
      strip-prefix: false
      sensitive-headers:
      service-id: checkout
    reservations:
      strip-prefix: false
      sensitive-headers:
      service-id: product
    products:
      strip-prefix: false
      sensitive-headers:
      service-id: product
    payments:
      strip-prefix: false
      sensitive-headers:
      service-id: payment
    service:
      service-id: eureka
      strip-prefix: false
      sensitive-headers:

