
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:48080/services/eureka}
  instance:
    preferIpAddress: true

spring:
  application:
    name: ${APP_NAME}

  main:
    banner-mode: 'off'

zuul:
  ignored-services: '*'
  routes:
    oauth:
      service-id: authz
      strip-prefix: false
      sensitive-headers:
    users:
      service-id: authz
      strip-prefix: false
      sensitive-headers:
    roles:
      service-id: authz
      strip-prefix: false
      sensitive-headers:
    baskets:
      service-id: basket
      strip-prefix: false
      sensitive-headers:
    customers:
      service-id: customer
      strip-prefix: false
      sensitive-headers:
    checkouts:
      service-id: checkout
      strip-prefix: false
      sensitive-headers:
    reservations:
      service-id: product
      strip-prefix: false
      sensitive-headers:
    products:
      service-id: product
      strip-prefix: false
      sensitive-headers:
    payments:
      service-id: payment
      strip-prefix: false
      sensitive-headers:
    services:
      service-id: eureka
      strip-prefix: false
      sensitive-headers:
