
database:
  host: ${APP_NAME}_db
  port: 5432

oauth:
  jwt:
    signKey: classpath:oauth.key
  clients:
    poc:
      secret: $2a$10$e9Dl5jmSyxQZoX15TkL5AOCeWOj.CQa3oWcjtX.kRQDfZtbrpfuga
      grantTypes:
        - password
        - authorization_code
        - refresh_token
        - client_credentials
      scopes:
        - read
        - write
      accessTokenValidity: 86400
      info:
        prop1: value
        prop2: 42
    eureka:
      secret: $2a$10$epNizivxoMaZAkg7JfYvMe9UvD2r0/2/NediAaTCROsiaISnvMfKC
      grantTypes:
        - password
        - authorization_code
        - refresh_token
        - client_credentials
      scopes:
        - read
        - write
        - eureka

spring:
  application:
    name: ${APP_NAME}

  datasource:
    username: ${APP_NAME}
    password: ${APP_NAME}
    url: jdbc:postgresql://${database.host}:${database.port}/${APP_NAME}

  flyway:
    check-location: false
    locations:
      - classpath:db
      - filesystem:${dataImportLocation:data}

  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
