
database:
  host: localhost
  port: 15432

server:
  port: 18080

spring:
  jackson:
    serialization.indent_output: true

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
