version: "3.1"

services:
  @application@-db:
    build:
      context: .
      dockerfile: database.txt
    image: @repository@@application@-db:latest
    container_name: @application@-db
    volumes:
      - @application@-db:/var/lib/postgresql/data/
      - @application@-pd:/usr/share/@application@/prod-data:ro
    environment:
      - POSTGRES_USER=@application@
      - POSTGRES_PASSWORD=@application@
      - POSTGRES_DB=@application@
    networks:
      - @network@
#    ports:
#      - "@jdbcPort@:5432"

  @application@:
    build:
      context: .
      dockerfile: application.txt
    image: @repository@@application@:latest
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
    depends_on:
      - @application@-db
    networks:
      - @network@
#    ports:
#      - "@httpPort1@-@httpPort2@:8080"
    volumes:
      - @application@-pd:/usr/share/@application@/prod-data:ro
    links:
      - "@application@-db"

volumes:
  @application@-db:
  @application@-pd:

networks:
  @network@:
