version: "3.1"

services:
  @application@:
    build:
      context: .
      dockerfile: application.txt
    image: @repository@@application@:latest
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
    networks:
      - @network@
    ports:
      - "@httpPort1@-@httpPort2@:8080"

networks:
  @network@:
