version: "3.1"

services:
  @application@-data:
    build:
      context: .
      dockerfile: populate.txt
    image: @repository@@application@-data:latest
    container_name: @application@-data
    networks:
      - @application@
    volumes:
      - @application@-data:/var/lib/@application@/data:ro

  @application@-db:
    build:
      context: .
      dockerfile: database.txt
    image: @repository@@application@-db:latest
    container_name: @application@-db
    volumes:
      - @application@-db:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=@application@
      - POSTGRES_PASSWORD=@application@
      - POSTGRES_DB=@application@
    networks:
      - @application@
#    ports:
#      - "@jdbcPort@:5432"

  @application@:
    build:
      context: .
      dockerfile: application.txt
    image: @repository@@application@:latest
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
    depends_on:
      - @application@-db
      - @application@-data
    networks:
      - @application@
    ports:
      - "@httpPort1@-@httpPort2@:8080"
    volumes:
      - @application@-data:/var/lib/@application@/data:ro
    links:
      - "@application@-db:db"

volumes:
  @application@-db:
  @application@-data:

networks:
  @application@:
