
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:48080/cloud/eureka}

server:
  servlet:
    context-path: /cloud

spring:
  application:
    name: ${APP_NAME}

  main:
    banner-mode: 'off'
