
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:48080/services/eureka/}

#server:
#  servlet:
#    context-path: /services

spring:
  application:
    name: ${APP_NAME}

  main:
    banner-mode: 'off'
