
database:
  host: localhost
  port: 20432

server:
  port: 23080

spring:
  jackson:
    serialization.indent_output: true

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  rabbitmq:
    host: localhost
