version: "3.1"

services:
  apache:
    build:
      context: .
      dockerfile: dockerfile.txt
    image: apache:latest
    container_name: apache
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
    networks:
      - micro-services
    ports:
      - "1080:80"

networks:
  micro-services:

