FROM archlinux/base

ARG SERVER_NAME

ENV SERVER_NAME $SERVER_NAME
RUN pacman -Syu --noconfirm
RUN pacman -S apache logrotate --needed --noconfirm
#RUN pacman -S vim iputils psmisc bind-tools inetutils --needed --noconfirm

RUN echo "Include host/*.conf" >>/etc/httpd/conf/httpd.conf
RUN mkdir -p /etc/httpd/host

COPY *.conf /etc/httpd/host
COPY run-httpd /usr/bin
RUN chmod +x /usr/bin/run-httpd

ENTRYPOINT [ "/usr/bin/run-httpd" ]

