version: "3.1"

services:
  apache:
    build:
      context: .
      dockerfile: dockerfile.txt
    image: [=repository][=application]:latest
    container_name: [=name]_[=application]
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
    networks:
      - [=network]
    ports:
      - "[=port]:80"

networks:
  [=network]:
