#!/bin/bash

[[ -z $SERVER_NAME ]] && SERVER_NAME=[=application]

set -e

rm -f /run/httpd/httpd.pid

for f in /var/log/httpd/*_log; do
	[[ -f $f ]] && rm -f $f
done

httpd -k start -DSERVER_NAME=$SERVER_NAME
sleep 5

tail -f /var/log/httpd/*_log

